require('dotenv').config();
const bcrypt = require('bcryptjs');
const mongoose = require('mongoose');
const User = require('./models/User');
const Job = require('./models/Job');
const Application = require('./models/Application');

const seedData = async () => {
  try {
    const connUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/careerconnect';
    await mongoose.connect(connUri);
    console.log('⚡ Connected to MongoDB for Tamil Nadu & India database seeding...');

    // Reset collections
    await User.deleteMany({});
    await Job.deleteMany({});
    await Application.deleteMany({});
    console.log('🧹 Cleared previous database collections.');

    const hashedPassword = await bcrypt.hash('Password@123', 10);

    // 1. Create Admin
    const admin = await User.create({
      name: 'Platform Admin',
      email: 'admin@careerconnect.com',
      password: hashedPassword,
      role: 'admin',
    });

    // 2. Create Recruiters in India & Tamil Nadu
    const googleRecruiter = await User.create({
      name: 'Sarah Connor',
      email: 'recruiter@google.com',
      password: hashedPassword,
      role: 'recruiter',
      company: 'Google India',
      companyIndustry: 'Technology',
      companyLocation: 'Chennai, Tamil Nadu',
      companySize: '10,000+',
      website: 'https://careers.google.com',
      recruiterPosition: 'Senior Talent Manager',
      isApproved: true,
    });

    const msRecruiter = await User.create({
      name: 'David Miller',
      email: 'recruiter@microsoft.com',
      password: hashedPassword,
      role: 'recruiter',
      company: 'Microsoft India',
      companyIndustry: 'Enterprise Software',
      companyLocation: 'Bengaluru, Karnataka (India)',
      companySize: '10,000+',
      website: 'https://careers.microsoft.com',
      recruiterPosition: 'Lead Recruiter',
      isApproved: true,
    });

    const startupRecruiter = await User.create({
      name: 'Alex Vance',
      email: 'recruiter@startup.io',
      password: hashedPassword,
      role: 'recruiter',
      company: 'TNElevate Tech',
      companyIndustry: 'FinTech Startup',
      companyLocation: 'Coimbatore, Tamil Nadu',
      companySize: '50-100',
      isApproved: true,
    });

    const amazonRecruiter = await User.create({
      name: 'Elena Rostova',
      email: 'recruiter@amazon.com',
      password: hashedPassword,
      role: 'recruiter',
      company: 'Amazon India',
      companyIndustry: 'Cloud & Commerce',
      companyLocation: 'Chennai, Tamil Nadu',
      companySize: '10,000+',
      isApproved: true,
    });

    const metaRecruiter = await User.create({
      name: 'Marcus Vance',
      email: 'recruiter@meta.com',
      password: hashedPassword,
      role: 'recruiter',
      company: 'Meta India Lab',
      companyIndustry: 'AI & Social Tech',
      companyLocation: 'Hyderabad, Telangana (India)',
      companySize: '10,000+',
      isApproved: true,
    });

    console.log('✅ Created Recruiter Accounts for India & Tamil Nadu');

    // 3. Create Job Seekers / Candidates
    const student1 = await User.create({
      name: 'Jane Doe',
      email: 'student1@university.edu',
      password: hashedPassword,
      role: 'student',
      careerStage: 'College Student',
      currentJobTitle: 'Computer Science Student',
      targetJobTitle: 'Full Stack Engineer',
      skills: ['React', 'Node.js', 'MongoDB', 'JavaScript', 'Git'],
      xp: 420,
    });

    const fresher = await User.create({
      name: 'Alex Rivera',
      email: 'fresher@university.edu',
      password: hashedPassword,
      role: 'student',
      careerStage: 'Fresher',
      currentJobTitle: 'Recent Graduate',
      targetJobTitle: 'Junior Developer',
      skills: ['Python', 'SQL', 'Django', 'REST APIs'],
      xp: 280,
    });

    const workingPro = await User.create({
      name: 'Marcus Vance',
      email: 'pro@techcorp.com',
      password: hashedPassword,
      role: 'student',
      careerStage: 'Working Professional',
      currentJobTitle: 'Software Engineer',
      targetJobTitle: 'Senior Full Stack Engineer',
      skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'Docker'],
      xp: 950,
    });

    console.log('✅ Created Candidate Accounts');

    // 4. Create Jobs — 6 JOBS PER CATEGORY IN TAMIL NADU & INDIA
    const jobDataList = [
      // ==========================================
      // CATEGORY 1: Full-time (6 Jobs)
      // ==========================================
      {
        title: 'Senior Full Stack Software Engineer',
        description: 'Lead architecture of enterprise cloud web suites servicing millions of global users from our Chennai technology hub.',
        company: 'Microsoft India',
        recruiter: msRecruiter._id,
        skillsRequired: ['React', 'TypeScript', 'Node.js', 'Azure', 'Docker'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Full-time',
        experienceLevel: 'Senior',
        industry: 'Software',
        targetCareerStages: ['Working Professional', 'Experienced Professional'],
        salaryRange: '₹18 LPA - ₹28 LPA ($22,000 - $34,000)',
        deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Backend Microservices Engineer',
        description: 'Design and optimize scalable distributed microservices powering high-throughput Cloud APIs in Bengaluru.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['Go', 'Python', 'Kubernetes', 'gRPC', 'PostgreSQL'],
        location: 'Bengaluru, Karnataka (India)',
        workPreference: 'Hybrid',
        jobType: 'Full-time',
        experienceLevel: 'Mid',
        industry: 'Technology',
        targetCareerStages: ['Working Professional', 'Fresher', 'Recent Graduate'],
        salaryRange: '₹16 LPA - ₹24 LPA ($19,000 - $29,000)',
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'AI & Machine Learning Research Lead',
        description: 'Research, train, and deploy state-of-the-art large language models and computer vision pipelines in Coimbatore.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['Python', 'PyTorch', 'TensorFlow', 'LLMs', 'C++'],
        location: 'Coimbatore, Tamil Nadu',
        workPreference: 'On-site',
        jobType: 'Full-time',
        experienceLevel: 'Senior',
        industry: 'Artificial Intelligence',
        targetCareerStages: ['Experienced Professional', 'Working Professional'],
        salaryRange: '₹20 LPA - ₹32 LPA ($24,000 - $38,000)',
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Cloud Infrastructure & DevOps Lead',
        description: 'Architect multi-region serverless and containerized deployment pipelines for cloud platforms in Hyderabad.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['AWS', 'Kubernetes', 'Terraform', 'Docker', 'Python'],
        location: 'Hyderabad, Telangana (India)',
        workPreference: 'Remote',
        jobType: 'Full-time',
        experienceLevel: 'Senior',
        industry: 'Cloud Infrastructure',
        targetCareerStages: ['Working Professional', 'Experienced Professional'],
        salaryRange: '₹19 LPA - ₹29 LPA ($23,000 - $35,000)',
        deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Junior Data Engineer & SQL Specialist',
        description: 'Build robust ETL data pipelines and business telemetry models supporting product teams in Trichy.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['Python', 'SQL', 'PostgreSQL', 'Pandas', 'Airflow'],
        location: 'Tiruchirappalli (Trichy), Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Full-time',
        experienceLevel: 'Entry',
        industry: 'FinTech',
        targetCareerStages: ['Fresher', 'Recent Graduate', 'Career Switcher', 'Entry Level'],
        salaryRange: '₹6 LPA - ₹10 LPA ($7,200 - $12,000)',
        deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'iOS & React Native Mobile Engineer',
        description: 'Craft beautiful, high-performance cross-platform mobile user experiences for Indian & global users.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['React Native', 'Swift', 'TypeScript', 'GraphQL', 'iOS'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Full-time',
        experienceLevel: 'Mid',
        industry: 'Mobile',
        targetCareerStages: ['Working Professional', 'Recent Graduate'],
        salaryRange: '₹14 LPA - ₹20 LPA ($17,000 - $24,000)',
        deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        status: 'open',
      },

      // ==========================================
      // CATEGORY 2: Part-time (6 Jobs)
      // ==========================================
      {
        title: 'Part-Time Frontend React Developer',
        description: 'Flexible 20 hrs/week building user-facing dashboard components and responsive UI modules in Chennai.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['React', 'JavaScript', 'CSS3', 'HTML5', 'Git'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Part-time',
        experienceLevel: 'Entry',
        industry: 'EdTech',
        targetCareerStages: ['College Student', 'School Student', 'Freelancer', 'Part-Time Job Seeker'],
        salaryRange: '₹25,000 - ₹40,000 / month',
        deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Part-Time Technical Content & Educator',
        description: 'Create technical documentation, coding tutorials, and developer guides for learners across Tamil Nadu & India.',
        company: 'Microsoft India',
        recruiter: msRecruiter._id,
        skillsRequired: ['Technical Writing', 'Markdown', 'Python', 'JavaScript'],
        location: 'Madurai, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Part-time',
        experienceLevel: 'Mid',
        industry: 'Developer Relations',
        targetCareerStages: ['College Student', 'Part-Time Job Seeker', 'Career Switcher'],
        salaryRange: '₹30,000 - ₹50,000 / month',
        deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Part-Time UI/UX Design Specialist',
        description: 'Design wireframes, user flow diagrams, and interactive prototypes for web and mobile apps.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['Figma', 'UI/UX Design', 'Prototyping', 'User Research'],
        location: 'Coimbatore, Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Part-time',
        experienceLevel: 'Mid',
        industry: 'Design',
        targetCareerStages: ['College Student', 'Freelancer', 'Part-Time Job Seeker'],
        salaryRange: '₹35,000 - ₹55,000 / month',
        deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Part-Time Data Entry & SQL Analyst',
        description: 'Assist product management team by querying databases, cleaning telemetry data, and generating reports.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['SQL', 'Excel', 'Data Cleaning', 'Python'],
        location: 'Salem, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Part-time',
        experienceLevel: 'Entry',
        industry: 'Analytics',
        targetCareerStages: ['College Student', 'Fresher', 'Part-Time Job Seeker', 'School Student'],
        salaryRange: '₹18,000 - ₹28,000 / month',
        deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Part-Time QA Test Automation Specialist',
        description: 'Conduct manual and automated integration testing on web apps before weekly deployment cycles.',
        company: 'Meta India Lab',
        recruiter: metaRecruiter._id,
        skillsRequired: ['Cypress', 'Selenium', 'JavaScript', 'QA Testing', 'Jira'],
        location: 'Bengaluru, Karnataka (India)',
        workPreference: 'Hybrid',
        jobType: 'Part-time',
        experienceLevel: 'Entry',
        industry: 'Quality Assurance',
        targetCareerStages: ['College Student', 'Part-Time Job Seeker', 'Entry Level'],
        salaryRange: '₹22,000 - ₹38,000 / month',
        deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Part-Time Customer Tech Support Lead',
        description: 'Provide technical guidance, API troubleshooting, and account support for developer community users in TN.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['API Troubleshooting', 'Customer Support', 'Zendesk', 'JSON'],
        location: 'Tiruchirappalli (Trichy), Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Part-time',
        experienceLevel: 'Entry',
        industry: 'Technical Support',
        targetCareerStages: ['School Student', 'College Student', 'Returning to Work', 'Part-Time Job Seeker'],
        salaryRange: '₹20,000 - ₹32,000 / month',
        deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        status: 'open',
      },

      // ==========================================
      // CATEGORY 3: Internship (6 Jobs)
      // ==========================================
      {
        title: 'Full Stack Software Engineering Intern',
        description: '12-week paid internship working on live product features in React, Node.js, and MongoDB in Chennai.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Git'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Internship',
        experienceLevel: 'Entry',
        industry: 'Software',
        targetCareerStages: ['College Student', 'School Student', 'Recent Graduate'],
        salaryRange: '₹25,000 - ₹45,000 / month stipend',
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'AI & Prompt Engineering Intern',
        description: 'Explore state-of-the-art LLM fine-tuning, RAG pipelines, and conversational agent evaluations in Bengaluru.',
        company: 'Meta India Lab',
        recruiter: metaRecruiter._id,
        skillsRequired: ['Python', 'PyTorch', 'REST APIs', 'LLMs', 'LangChain'],
        location: 'Bengaluru, Karnataka (India)',
        workPreference: 'Remote',
        jobType: 'Internship',
        experienceLevel: 'Entry',
        industry: 'Artificial Intelligence',
        targetCareerStages: ['College Student', 'Recent Graduate'],
        salaryRange: '₹30,000 - ₹50,000 / month stipend',
        deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Product Design & UX Research Intern',
        description: 'Collaborate with senior designers to conduct user interviews, build wireframes, and design UI components.',
        company: 'Microsoft India',
        recruiter: msRecruiter._id,
        skillsRequired: ['Figma', 'UI/UX Design', 'User Research', 'Wireframing'],
        location: 'Coimbatore, Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Internship',
        experienceLevel: 'Entry',
        industry: 'Product Design',
        targetCareerStages: ['College Student', 'School Student', 'Recent Graduate'],
        salaryRange: '₹20,000 - ₹35,000 / month stipend',
        deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Cloud Security & Networking Intern',
        description: 'Learn enterprise cloud perimeter defense, network packet inspection, and vulnerability remediation.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['Linux', 'Networking', 'Python', 'Cybersecurity', 'AWS'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'On-site',
        jobType: 'Internship',
        experienceLevel: 'Entry',
        industry: 'Cybersecurity',
        targetCareerStages: ['College Student', 'Fresher', 'Recent Graduate'],
        salaryRange: '₹22,000 - ₹40,000 / month stipend',
        deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Data Science & Machine Learning Intern',
        description: 'Build predictive statistical models and data visualization pipelines supporting consumer insights.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['Python', 'SQL', 'Pandas', 'Scikit-Learn', 'Statistics'],
        location: 'Madurai, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Internship',
        experienceLevel: 'Entry',
        industry: 'Data Science',
        targetCareerStages: ['College Student', 'School Student', 'Recent Graduate'],
        salaryRange: '₹18,000 - ₹30,000 / month stipend',
        deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'DevOps & Systems Automation Intern',
        description: 'Automate build infrastructure, Docker containers, and CI/CD deployment workflows.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['Docker', 'Linux', 'Bash', 'Git', 'Python'],
        location: 'Hyderabad, Telangana (India)',
        workPreference: 'Remote',
        jobType: 'Internship',
        experienceLevel: 'Entry',
        industry: 'DevOps',
        targetCareerStages: ['College Student', 'Recent Graduate'],
        salaryRange: '₹25,000 - ₹42,000 / month stipend',
        deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        status: 'open',
      },

      // ==========================================
      // CATEGORY 4: Contract (6 Jobs)
      // ==========================================
      {
        title: 'Contract Senior React Frontend Architect (6 Months)',
        description: '6-month contract spearheading complex state management overhaul and performance tuning in Chennai.',
        company: 'Microsoft India',
        recruiter: msRecruiter._id,
        skillsRequired: ['React', 'Redux Toolkit', 'TypeScript', 'Webpack', 'Performance'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Contract',
        experienceLevel: 'Senior',
        industry: 'Enterprise Software',
        targetCareerStages: ['Working Professional', 'Experienced Professional', 'Freelancer'],
        salaryRange: '₹1,200 - ₹2,000 / hr (₹15-25 LPA equivalent)',
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Contract Multi-Cloud Migration Engineer (9 Months)',
        description: 'Lead migration of legacy infrastructure and database workloads from AWS to Azure hybrid cloud.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['AWS', 'Azure', 'Terraform', 'Cloud Migration', 'Kubernetes'],
        location: 'Bengaluru, Karnataka (India)',
        workPreference: 'Hybrid',
        jobType: 'Contract',
        experienceLevel: 'Senior',
        industry: 'Cloud Computing',
        targetCareerStages: ['Experienced Professional', 'Working Professional'],
        salaryRange: '₹1,500 - ₹2,500 / hr',
        deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Contract Cybersecurity Compliance Consultant',
        description: 'Audit cloud infrastructure against SOC2 Type II and ISO27001 standards and implement security policies in TN.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['SOC2', 'ISO27001', 'Penetration Testing', 'Cybersecurity', 'Audit'],
        location: 'Coimbatore, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Contract',
        experienceLevel: 'Senior',
        industry: 'Security',
        targetCareerStages: ['Experienced Professional', 'Freelancer'],
        salaryRange: '₹1,800 - ₹2,800 / hr',
        deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Contract High-Performance Golang Engineer',
        description: 'Develop low-latency order execution services and gRPC APIs for financial transaction engine.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['Go', 'gRPC', 'PostgreSQL', 'Redis', 'Microservices'],
        location: 'Tiruchirappalli (Trichy), Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Contract',
        experienceLevel: 'Mid',
        industry: 'FinTech',
        targetCareerStages: ['Working Professional', 'Experienced Professional'],
        salaryRange: '₹1,000 - ₹1,800 / hr',
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Contract PostgreSQL Database Specialist',
        description: 'Optimize complex query execution plans, partition massive tables, and configure high availability replication.',
        company: 'Meta India Lab',
        recruiter: metaRecruiter._id,
        skillsRequired: ['PostgreSQL', 'SQL Optimization', 'Database Tuning', 'Redis'],
        location: 'Hyderabad, Telangana (India)',
        workPreference: 'Remote',
        jobType: 'Contract',
        experienceLevel: 'Senior',
        industry: 'Database Infrastructure',
        targetCareerStages: ['Experienced Professional', 'Working Professional'],
        salaryRange: '₹1,400 - ₹2,200 / hr',
        deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Contract Mobile App Developer (Flutter / React Native)',
        description: 'Build custom cross-platform mobile modules for enterprise logistics tracking application.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['Flutter', 'React Native', 'Firebase', 'REST APIs'],
        location: 'Salem, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Contract',
        experienceLevel: 'Mid',
        industry: 'Logistics Tech',
        targetCareerStages: ['Working Professional', 'Freelancer'],
        salaryRange: '₹900 - ₹1,500 / hr',
        deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        status: 'open',
      },

      // ==========================================
      // CATEGORY 5: Freelance (6 Jobs)
      // ==========================================
      {
        title: 'Freelance Full Stack Web Application Developer',
        description: 'Deliver end-to-end custom client web portal with React frontend, Node backend, and Payment integration.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['React', 'Node.js', 'Express', 'MongoDB', 'Stripe API'],
        location: 'Chennai, Tamil Nadu (Remote)',
        workPreference: 'Remote',
        jobType: 'Freelance',
        experienceLevel: 'Mid',
        industry: 'Web Development',
        targetCareerStages: ['Freelancer', 'Working Professional', 'Career Switcher'],
        salaryRange: '₹800 - ₹1,400 / hr',
        deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Freelance Python Data Automation Specialist',
        description: 'Create automated data extraction scripts, web scrapers, and automated notification integrations.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['Python', 'BeautifulSoup', 'Selenium', 'Web Scraping', 'APIs'],
        location: 'Coimbatore, Tamil Nadu (Remote)',
        workPreference: 'Remote',
        jobType: 'Freelance',
        experienceLevel: 'Entry',
        industry: 'Automation',
        targetCareerStages: ['Freelancer', 'College Student', 'Part-Time Job Seeker'],
        salaryRange: '₹600 - ₹1,000 / hr',
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Freelance Brand Identity & Graphic Designer',
        description: 'Design complete brand style guides, logo assets, UI design tokens, and vector illustration packs.',
        company: 'Meta India Lab',
        recruiter: metaRecruiter._id,
        skillsRequired: ['Figma', 'Adobe Illustrator', 'Branding', 'Graphic Design'],
        location: 'Madurai, Tamil Nadu (Remote)',
        workPreference: 'Remote',
        jobType: 'Freelance',
        experienceLevel: 'All Levels',
        industry: 'Design & Creative',
        targetCareerStages: ['Freelancer', 'College Student', 'Part-Time Job Seeker'],
        salaryRange: '₹700 - ₹1,200 / hr',
        deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Freelance Technical SEO & Web Performance Specialist',
        description: 'Audit website Core Web Vitals, implement structured schema data, and optimize lighthouse scores.',
        company: 'Microsoft India',
        recruiter: msRecruiter._id,
        skillsRequired: ['SEO', 'Next.js', 'Core Web Vitals', 'Google Analytics'],
        location: 'Bengaluru, Karnataka (India)',
        workPreference: 'Remote',
        jobType: 'Freelance',
        experienceLevel: 'Mid',
        industry: 'Digital Growth',
        targetCareerStages: ['Freelancer', 'Working Professional'],
        salaryRange: '₹900 - ₹1,500 / hr',
        deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Freelance WordPress & E-Commerce Developer',
        description: 'Build custom WooCommerce and Shopify store themes with tailored payment gateways for Indian merchants.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['WordPress', 'PHP', 'Shopify', 'WooCommerce', 'CSS3'],
        location: 'Tiruchirappalli (Trichy), Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Freelance',
        experienceLevel: 'Entry',
        industry: 'E-Commerce',
        targetCareerStages: ['Freelancer', 'Career Switcher', 'Part-Time Job Seeker'],
        salaryRange: '₹500 - ₹900 / hr',
        deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Freelance Technical Blog Author & Copywriter',
        description: 'Write engaging, highly technical articles on cloud architecture, AI workflows, and software development.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['Technical Writing', 'Copywriting', 'SEO', 'Developer Docs'],
        location: 'Chennai, Tamil Nadu (Remote)',
        workPreference: 'Remote',
        jobType: 'Freelance',
        experienceLevel: 'Entry',
        industry: 'Content & Media',
        targetCareerStages: ['Freelancer', 'College Student', 'Returning to Work'],
        salaryRange: '₹500 - ₹850 / hr',
        deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        status: 'open',
      },

      // ==========================================
      // CATEGORY 6: Apprenticeship (6 Jobs)
      // ==========================================
      {
        title: 'Software Engineering Apprentice (TN Launchpad)',
        description: 'Structured 12-month paid apprenticeship combining hands-on coding mentorship with live production work in Chennai.',
        company: 'Microsoft India',
        recruiter: msRecruiter._id,
        skillsRequired: ['Java', 'Python', 'Software Fundamentals', 'Git', 'Problem Solving'],
        location: 'Chennai, Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Apprenticeship',
        experienceLevel: 'Entry',
        industry: 'Software Engineering',
        targetCareerStages: ['College Student', 'School Student', 'Fresher', 'Career Switcher'],
        salaryRange: '₹20,000 - ₹32,000 / month stipend',
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Cybersecurity Defense & Ops Apprentice',
        description: '1-year training program learning security operations center (SOC) monitoring, threat detection, and response.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['Networking', 'Linux', 'Security Fundamentals', 'Wireshark'],
        location: 'Coimbatore, Tamil Nadu',
        workPreference: 'On-site',
        jobType: 'Apprenticeship',
        experienceLevel: 'Entry',
        industry: 'Cybersecurity',
        targetCareerStages: ['Career Switcher', 'Recent Graduate', 'Fresher', 'School Student'],
        salaryRange: '₹22,000 - ₹35,000 / month stipend',
        deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Cloud & DevOps Engineering Apprentice',
        description: 'Learn Linux administration, containerization, and cloud deployment pipelines under senior mentors in Bengaluru.',
        company: 'Amazon India',
        recruiter: amazonRecruiter._id,
        skillsRequired: ['Linux', 'Bash', 'AWS Fundamentals', 'Docker', 'Python'],
        location: 'Bengaluru, Karnataka (India)',
        workPreference: 'Hybrid',
        jobType: 'Apprenticeship',
        experienceLevel: 'Entry',
        industry: 'Cloud Infrastructure',
        targetCareerStages: ['Fresher', 'Career Switcher', 'College Student', 'Entry Level'],
        salaryRange: '₹24,000 - ₹38,000 / month stipend',
        deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Frontend Web Development Apprentice',
        description: 'Intensive 9-month apprenticeship focusing on modern HTML, CSS, JavaScript, and React framework building.',
        company: 'TNElevate Tech',
        recruiter: startupRecruiter._id,
        skillsRequired: ['HTML5', 'CSS3', 'JavaScript', 'React Basics', 'Git'],
        location: 'Madurai, Tamil Nadu',
        workPreference: 'Remote',
        jobType: 'Apprenticeship',
        experienceLevel: 'Entry',
        industry: 'Web Engineering',
        targetCareerStages: ['Career Switcher', 'School Student', 'College Student', 'Returning to Work'],
        salaryRange: '₹18,000 - ₹28,000 / month stipend',
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Data Engineering & SQL Analytics Apprentice',
        description: 'Learn data warehousing, SQL query optimization, and automated reporting pipelines from industry leaders.',
        company: 'Meta India Lab',
        recruiter: metaRecruiter._id,
        skillsRequired: ['SQL', 'Python', 'Data Warehousing', 'Excel', 'Problem Solving'],
        location: 'Hyderabad, Telangana (India)',
        workPreference: 'Hybrid',
        jobType: 'Apprenticeship',
        experienceLevel: 'Entry',
        industry: 'Data Engineering',
        targetCareerStages: ['Career Switcher', 'Fresher', 'Recent Graduate', 'College Student'],
        salaryRange: '₹22,000 - ₹35,000 / month stipend',
        deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
      {
        title: 'Digital Product & UI/UX Design Apprentice',
        description: 'Hands-on design apprenticeship building design systems, interactive prototypes, and accessible user flows.',
        company: 'Google India',
        recruiter: googleRecruiter._id,
        skillsRequired: ['Figma', 'UI Design', 'Wireframing', 'Prototyping'],
        location: 'Tiruchirappalli (Trichy), Tamil Nadu',
        workPreference: 'Hybrid',
        jobType: 'Apprenticeship',
        experienceLevel: 'Entry',
        industry: 'Product Design',
        targetCareerStages: ['School Student', 'College Student', 'Career Switcher', 'Returning to Work'],
        salaryRange: '₹20,000 - ₹30,000 / month stipend',
        deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        status: 'open',
      },
    ];

    const jobs = await Job.insertMany(jobDataList);
    console.log(`✅ Successfully Created ${jobs.length} Jobs in Tamil Nadu & India!`);

    // 5. Create Sample Applications with notifications
    await Application.create({
      job: jobs[0]._id,
      student: student1._id,
      coverNote: 'I build modern React & Node apps and would love to join Microsoft India in Chennai!',
      status: 'shortlisted',
    });

    await Application.create({
      job: jobs[1]._id,
      student: workingPro._id,
      coverNote: '4 years experience with full-stack React and Go microservices. Excited about Google Cloud India!',
      status: 'interview',
      interviewDetails: {
        date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        type: 'System Design Interview',
        note: 'Prepare system architecture diagram for multi-region microservice scaling.',
      },
    });

    await Application.create({
      job: jobs[4]._id,
      student: fresher._id,
      coverNote: 'Combining Python and SQL skills. Ready to start full time as Junior Data Engineer in Trichy.',
      status: 'pending',
    });

    console.log('✅ Created Sample Applications & Interview Schedules');

    console.log('\n======================================================');
    console.log('🎉 DATABASE SEEDED WITH TAMIL NADU & INDIA LOCATIONS!');
    console.log('======================================================');
    console.log('Location Highlights:');
    console.log('  • Chennai, Tamil Nadu');
    console.log('  • Coimbatore, Tamil Nadu');
    console.log('  • Madurai, Tamil Nadu');
    console.log('  • Tiruchirappalli (Trichy), Tamil Nadu');
    console.log('  • Salem, Tamil Nadu');
    console.log('  • Bengaluru, Karnataka (India)');
    console.log('  • Hyderabad, Telangana (India)');
    console.log(`  • TOTAL JOBS: ${jobs.length} jobs`);
    console.log('======================================================\n');

    process.exit(0);
  } catch (err) {
    console.error('❌ Error seeding database:', err.message);
    process.exit(1);
  }
};

seedData();
